### ISSUE TITLE
'paper-header-transform' fires too often on touch screen and locks up animation (freezes)

### ISSUE THREAD

**Issue by Where-Solutions** [PolymerElements/polymer-starter-kit#756] opened 2016-03-17 19:30 UTC
If you take a PSK app, for example https://polymer-starter-kit.firebaseapp.com/, open on a phone (my Nexus 5), and open/close the Title Bar to watch the cool animation, then eventually the header will freeze, the menu will be un-resonsive and a page refresh will not fix it. You have to close the browser and re-open it.

I tried to incorporate the "Polymer.Base.debounce", but could not get it to work. So my hack for now is:

```
      if(ws.scrollTimer){
        clearTimeout(ws.scrollTimer);
      }

      ws.scrollTimer = setTimeout(function(){
        console.log('paper-header-transform executed e = ' + e.detail);
        ws.setHeaderVars(e);
        // Move/translate middleContainer
        Polymer.Base.transform('translate3d(0,' + ws.yRatio * 100 + '%,0)', ws.middleContainer);

        // Scale bottomContainer and bottom sub title to nothing and back
        Polymer.Base.transform('scale(' + ws.scaleBottom + ') translateZ(0)', ws.bottomContainer);

        // Scale middleContainer appName
        Polymer.Base.transform('scale(' + ws.scaleMiddle + ') translateZ(0)', ws.appName);
    }, 50);
```
"ws" is my namespace.

It would be nice to see an example of how to do this with Polymer.Base.debounce.

**Comment by samccone** [comment] 2016-03-17 20:44
Hey @Where-Solutions 

When you say > and open/close the Title Bar

Can you describe your testing methodology :)


Thanks for the issue!

**Comment by Where-Solutions** [comment] 2016-03-18 01:19
Just tested PSK 1.3.0 sample https://polymerelements.github.io/polymer-starter-kit/ and issue is still there.

If you put your finger (phone only) on the content and move up and down (like a twit) to show the header animation, the animated header will eventually freeze and become unresponsive. Since the header animation is cool, some users will play with it too much. It needs to be more idiot proof.

**Comment by robdodson** [comment] 2016-03-18 16:44
Can you tell us more about the phone and browser you're using?

I'm not able to reproduce this on a Nexus 5X running Chrome for Android. Haven't tested on an iOS device yet.

**Comment by Where-Solutions** [comment] 2016-03-19 01:48
Hi, I have a Nexus5 and Chrome, version 49.0.2623.91. You just have to wiggle the content div so that the header is animating up/down, then it freezes. Only takes about 5 seconds. It seems to happen when the header only partially open/close, then asked to go the other way. It freezes at a midpoint in the animation.

**Comment by gaurav21r** [comment] 2016-03-21 06:17
@Where-Solutions Are you using Chrome for Android or via the  Chrome WebView in a apckaged app like Cordova? Maybe a screencast will help!

**Comment by Where-Solutions** [comment] 2016-03-21 17:53
Just the standard Chrome for Android. How would you make a screencast of the phone?

**Comment by Where-Solutions** [comment] 2016-03-21 18:06
Hey! I learned a new skill. Here is a YouTube video of the header freezing:

https://youtu.be/dHhAQRN4n9c

**Comment by robdodson** [comment] 2016-03-21 18:58
interesting. it looks like the whole header panel breaks.


if you remove this block of code are you still able to break it?
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/scripts/app.js#L48-L70

**Comment by chuckh** [comment] 2016-03-21 20:20
I tested on Nexus 7 with Android 6.0.1 and Chrome 49, also tested on Moto G with Android 5.1.0 and Chrome 45 and could not reproduce this issue. @Where-Solutions what version of Android and Chrome are you using?

**Comment by samccone** [comment] 2016-03-21 20:21
also @Where-Solutions do you have any chrome-extensions? like last-pass or anything?

**Comment by Where-Solutions** [comment] 2016-03-22 01:12
@chuckh - Seems to happen with small finger up/down movements near the top of the content.
@samccone - very stock Nexus 5, don't think anything has changed on phone, will try other phones as well.
@robdodson  - I put that block of code in a setTimeout/clearTimeout hack to make my apps not freeze. I was looking for something more elegant. (see ws.scrollTimer in original post) Also I tried moving some of the code to another function to see if that would help. Users love the cool header animation, so I was trying to fix it so they cannot break it if they play too much. Works fine if you are not a spazz.

**Comment by vguillou** [comment] 2016-03-22 08:10
I gave it a try and I can confirm the issue here (Chrome 49 on a Moto X 2014 running Android 6.0.0).
The key to reproduce is to quickly and successively change the scrolling direction when the header is still being transformed, while it's not completely condensed or stretched.
It can take a while to freeze though.

The issue is most definitely linked to the last 2 scale transformations (https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/scripts/app.js#L65-L69) as I can't reproduce when I comment them out.

**Comment by addyosmani** [comment] 2016-03-22 10:03
It's really tricky to reproduce this issue, but it's definitely there. I think we've generally not been too aggressive on testing the change in scroll directions in the way outlined in the video. I'm surprised the scale transformations are getting stuck. Marking as a bug for us to dig into further.

**Comment by Where-Solutions** [comment] 2016-03-22 16:13
Thank you Polymer Team for your diligence and amazing efforts.

**Comment by NicolasRannou** [comment] 2016-03-23 08:28
LG G4 - Android 6.0

Chrome stable (32 bits): 49.0.2623.91 -> can reproduce bug easily (actually scrolling slowly..)
Chrome beta (**32 bits**): 50.0.2661.35 (**V8 5.0.71**)-> can reproduce bug easily
Chrome dev (**64 bits**): 51.0.2681.4 (**V8 5.1.146**) -> can NOT reproduce bug

Not sure if the V8 upgrade could have fixed it somehow or if the 64 bits are just hiding the problem.

**Comment by robdodson** [comment] 2016-08-27 18:14
We're no longer using paper-scroll-header-panel in PSK. Any issues relating to the [app-layout](https://github.com/PolymerElements/app-layout) elements should be opened on that repo.

**Closed by robdodson** 2016-08-27 18:14 UTC
Labels: bug
