### ISSUE TITLE
Failed at the polymer-starter-kit@0.0.0 deps script 'npm install -g gulp && npm install -g bower && npm install && bower install'.

### ISSUE THREAD

**Issue by harshakakumanu1** [PolymerElements/polymer-starter-kit#99] opened 2015-06-01 23:52 UTC
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'deps' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose run-script [ 'predeps', 'deps', 'postdeps' ]
5 info predeps polymer-starter-kit@0.0.0
6 info deps polymer-starter-kit@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info polymer-starter-kit@0.0.0 Failed to exec deps script
9 verbose stack Error: polymer-starter-kit@0.0.0 deps: `npm install -g gulp && npm install -g bower && npm install && bower install`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid polymer-starter-kit@0.0.0
11 verbose cwd /Users/harshavardhan/Desktop/poly
12 error Darwin 14.4.0
13 error argv "node" "/usr/local/bin/npm" "run" "deps"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error polymer-starter-kit@0.0.0 deps: `npm install -g gulp && npm install -g bower && npm install && bower install`
17 error Exit status 1
18 error Failed at the polymer-starter-kit@0.0.0 deps script 'npm install -g gulp && npm install -g bower && npm install && bower install'.
18 error This is most likely a problem with the polymer-starter-kit package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install -g gulp && npm install -g bower && npm install && bower install
18 error You can get their info via:
18 error     npm owner ls polymer-starter-kit
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by addyosmani** [comment] 2015-06-01 23:55
Duplicate of https://github.com/PolymerElements/polymer-starter-kit/issues/76. If running `npm install -g gulp && npm install -g bower && npm install && bower install` in the downloaded Starter Kit directory doesn't help, you may need to fix up your permissions. 

Sorry for the extra hassle, but the comments in that thread should help.

**Closed by addyosmani** 2015-06-01 23:55 UTC
