### ISSUE TITLE
Double click menu issue in Firefox/Safari/Explorer

### ISSUE THREAD

**Issue by carlosbkm** [PolymerElements/polymer-starter-kit#299] opened 2015-08-07 10:12 UTC
The left panel menu works fluid in Chrome and responds to one click as expected. However in Firefox it's necessary to double click on the items to go the corresponding section. In Internet Explorer (last versions) it happens the same, and in Safari the behaviour is quite erratic (sometimes it works with one click, sometimes not).

Do you have any idea why is this happening? Could it be a problem of page.js, the polymer components itself, or just the browsers other than Chrome not supporting Polymer as expected?

If you know any work around to solve this, I would really appreciate it.

**Comment by dalu** [comment] 2015-08-07 14:03
https://github.com/PolymerElements/polymer-starter-kit/issues/166

**Comment by arthurvr** [comment] 2015-08-18 16:10
Duplicate of #166, as @dalu pointed out. Let's close this issue.

**Comment by arthurvr** [comment] 2015-08-21 21:00
@addyosmani @chuckh @samccone Ping-ping, can anyone close this as a dupe? :)

**Closed** 2015-08-21 21:02 UTC
