### ISSUE TITLE
Button highlighted on browser restore

### ISSUE THREAD

**Issue by bflora2** [PolymerElements/polymer-starter-kit#295] opened 2015-08-05 16:17 UTC
Scenario: Click a paper elements toolbar icon button and then minimize the browser window to the taskbar. Then restore the browser window. The toolbar button is now inappropriately highlighted. This issue can be seen in IE and Firefox. The [toolbar demo] (https://elements.polymer-project.org/elements/paper-toolbar?view=demo:demo/index.html) at the Polymer catalog is sufficient to demonstrate the issue.

**Comment by addyosmani** [comment] 2015-08-05 17:01
Is this a PSK specific-issue or an issue with https://github.com/PolymerElements/paper-toolbar? By the sounds of it the issue needs to be reported upstream and we can then bump our dependencies accordingly but will wait for you to confirm :)

**Comment by robdodson** [comment] 2015-08-05 20:41
I think this is an issue with paper-ripple. I've seen it on checkboxes as well when switching tabs

**Comment by addyosmani** [comment] 2015-08-06 11:33
Thanks @robdodson. I think it's an upstream issue too. Will wait on @bflora2 to confirm, but I think this is probably better handled on the ripples repo.

**Comment by bflora2** [comment] 2015-08-06 15:00
> Is this a PSK specific-issue

I don't think so since the problem can be seen in the toolbar demo of the Polymer catalog. Sorry for the confusion. Is there a preferred place to report paper element issues, or do I need to search through the various PolymerElements projects in Github to try to find the most appropriate one for a particular issue?

**Comment by robdodson** [comment] 2015-08-11 15:33
I think I see the problem: https://github.com/PolymerElements/paper-icon-button/issues/25

This may be working as intended to show a returning user their current focus state

**Comment by bflora2** [comment] 2015-08-11 16:48
Hmm... That is not typical of how UI controls normally work. In general, if a UI control displays its focus state then it does so whenever it has focus, not just when the parent app regains focus after focus loss. In my case, this behavior is happening for a toolbar button, and toolbar buttons are rarely designed to display focus, so it looks strange if they do so. At the very least, the programmer should be able to disable this behavior. Your thoughts?

**Comment by robdodson** [comment] 2015-08-11 17:28
@bflora2 I did a quick test by adding an anchor element to a page, focusing it with the keyboard, minimizing the browser, and restoring the browser. In that situation, a focus ring remains on the anchor.

However, you don't see this same behavior if you click on the anchor. So it seems like there are different behaviors depending on how you interacting with the element.

cc @blasten @notwaldorf @cdata

**Comment by bflora2** [comment] 2015-08-11 20:52
> I did a quick test by adding an anchor element to a page, focusing it with the keyboard, minimizing the 
> browser, and restoring the browser. In that situation, a focus ring remains on the anchor.

@robdodson Now that you mention it, I notice paper icon buttons display focus when you tab to them. But there should be a concept of paper element icon buttons that can not receive focus. For example, if you tab through all the focusable page elements and browser controls in your browser you will notice the browser's toolbar buttons never receive focus because they are not focusable controls. That is typical behavior for toolbar buttons in various UI platforms, but it seems to be missing in paper element toolbar buttons (please correct me if I've missed it).

> However, you don't see this same behavior if you click on the anchor. So it seems like there are 
> different behaviors depending on how you are interacting with the element.

The behavior seems to vary among browsers as well. I see Firefox displays the focus ring for mouse clicks but Chrome does not. In any case, I can always choose to not display a link's focus ring by applying style `outline: 0` to the link. At the least, we should be able to do do something similar with paper elements, but it would better if paper elements could be designated as non-focusable so elements like toolbar buttons would have appropriate behavior.

cc @blasten @notwaldorf @cdata

**Comment by robdodson** [comment] 2015-08-11 21:00
Your first point doesn't seem correct. If you look at any control element, `<a>`, `<button>`, `<input>`, they're all implicitly focusable.

> In any case, I can always choose to not display a link's focus ring by applying style outline: 0 to the link. At the least, we should be able to do do something similar with paper elements, but it would better if paper elements could be designated as non-focusable so elements like toolbar buttons would have appropriate behavior.

If you want something to be non-focusable you can add `tabindex=-1`. But it sounds like you want to distinguish between mouse and keyboard focus, and *not* apply focus states if it came from a mouse. You absolutely must apply focus states if it came from a keyboard, otherwise a motor impaired user who is navigating with the keyboard is not going to be able to tell where focus is on your page. Most paper elements apply a `focused` attribute when they are keyboard focused, so if you want to remove the focus state just for mouse I think you could use a selector like `paper-button:not([focused])` to change the focus behavior for mouse.

**Comment by bflora2** [comment] 2015-08-11 23:05
> If you look at any control element, <a>, <button>, <input>, they're all implicitly focusable.

Correct, and that's fine. But my point is that some UI controls, such as toolbar buttons, are typically not focusable. For example, you can't focus the buttons on your browser's toolbar via keyboard or mouse.

> If you want something to be non-focusable you can add tabindex=-1

Ah, yes, that's it. Thank you!

> You absolutely must apply focus states if it came from a keyboard, otherwise a motor impaired user 
> who is navigating with the keyboard is not going to be able to tell where focus is on your page.

That doesn't apply to toolbar buttons because those controls are designed for mice only. Again, you will see that your browser's toolbar buttons can not be focused via the keyboard. The reason is because toolbars are traditionally only meant to be a graphical convenience for sighted users. The programmer is still expected to provide a menu for accessibility.

In any case, if an element is supposed to display its focus state then it seems to me it should always do so, not just suddenly do it after the browser has lost and regained focus. If you disagree that's fine and I will consider the matter closed since you have provided me with a solution. Thanks again!

**Comment by robdodson** [comment] 2015-08-12 17:59
> But my point is that some UI controls, such as toolbar buttons, are typically not focusable. For example, you can't focus the buttons on your browser's toolbar via keyboard or mouse.

That's because the browser's UI is not written in HTML. If you're building a web app, in HTML, and you have a toolbar, then the buttons should have focus states of some kind. Perhaps I'm not understanding what you mean when you say 'toolbar'.

Using Google Drive as an example, I consider their top row of buttons a toolbar, and you can tab through those to focus them.

ex:

![screen shot 2015-08-12 at 10 55 09 am](https://cloud.githubusercontent.com/assets/1066253/9232164/f748116a-40e0-11e5-8c34-1c953541a20f.png)

Likewise with GitHub:

![screen shot 2015-08-12 at 10 58 00 am](https://cloud.githubusercontent.com/assets/1066253/9232175/117be6a6-40e1-11e5-92d7-a991fb2ab47a.png)

**Comment by alice** [comment] 2015-08-12 18:22
@bflora2 I think you're mistaken about toolbar buttons generally not being focusable. @robdodson pointed out Google Drive; you can also see this in Google Docs if you move focus away from the text input area by clicking on a menu or pressing Alt+F, and then pressing Tab a few times. You'll see that they carefully manage what is focusable: the menus as a whole are one tab stop, with arrow keys allowing you to navigate inside them; then, there is a link, and then the very next tab stop is the toolbar. You can then use arrow keys to navigate within the toolbar.

The ARIA design patterns doc describes exactly this behaviour: http://www.w3.org/TR/wai-aria-practices/#toolbar

As much as possible, please make _all_ of your visible UI accessible without a mouse. It's an extra toll on anyone who can't use a mouse to discover things within menus, or learn about special purpose keyboard shortcuts.

**Comment by bflora2** [comment] 2015-08-12 19:41
> I think you're mistaken about toolbar buttons generally not being focusable. @robdodson pointed 
> out Google Drive; you can also see this in Google Docs

Granted, my programming experience is mainly in the desktop world where the expectation of toolbar button behavior is somewhat different. And unfortunately, my reference to the browser's toolbar button behavior has caused a drift away from the *original* issue...

Let's look at the Google Docs toolbar since you referenced that as a proper example: If I keyboard over to the Undo toolbar icon button it displays a focus ring. If I then minimize/restore the browser window the Undo button still displays the focus ring. That's fine. Now, I click the Undo button and note that no focus ring is displayed. If I then minimize/restore the browser window I note that the Undo button does *not* suddenly decide to display a focus ring. Why is the expectation for paper toolbar icon buttons different?

**Comment by robdodson** [comment] 2015-08-12 19:50
The expectation shouldn't be different, that's kinda what I was getting at
above when I mentioned the need to distinguish between mouse and keyboard
focus. Right now it seems that paper-icon-button is being overly aggressive
with mouse focus states and that should probably be tweaked. If you want to
work around it in your own app I think you can use the style selector I
provided (or some variation of it). That way the keyboard folks will still
get focus, and you can disable it for the mouse folks.

**Comment by bflora2** [comment] 2015-08-12 20:05
> it seems that paper-icon-button is being overly aggressive with mouse focus states and that should 
> probably be tweaked.

Sounds good.

> If you want to work around it in your own app I think you can use the style selector I provided (or 
> some variation of it).

Thank you (and Alice) for your detailed responses. I really like the look and feel paper elements lend to my new project, and I appreciate the great work you folks are doing!

**Comment by robdodson** [comment] 2015-12-19 16:31
I'm going to close this as "working as intended".

If anyone is curious about why tabbing to an anchor or button produces a focus ring, but clicking on it does not, whereas if you give something a `:focus` style it *always* has a focus ring, you should read this article on input modality: http://radar.oreilly.com/2015/08/proposing-css-input-modailty.html

The tl;dr is that browsers use special internal magic to detect how someone interacted with an element (either via mouse or keyboard) and based on that knowledge, they either apply a focus ring (in the case of keyboard) or they don't (in the case of a mouse). The assumption is that if someone is using a mouse, they probably don't want the focus ring to appear on the thing they just clicked on. However, as soon as you give something a `:focus` style, all bets are off. Alice's proposal would allow an easy way to query for the input modality (was this a mouse or keyboard click?) and then selectively apply a style based on that knowledge.

Note there's also the non-standard [:-moz-focusring pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/%3A-moz-focusring) which provides similar functionality (though the name is a bit wonky). I've heard that folks on the Blink team proposed standardizing this across the board but it hasn't been done yet so keep your eyes peeled for that if you're an a11y nerd like me :dancer:

**Closed by robdodson** 2015-12-19 16:31 UTC
Labels: question
