### ISSUE TITLE
gulp default task doesn't copy images to dist/

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/polymer-starter-kit#446] opened 2015-10-19 09:26 UTC
On master (https://github.com/PolymerElements/polymer-starter-kit/commit/5672469c8814cfd0227cb2e260e08e51d713b793)

```
$> git clone https://github.com/PolymerElements/polymer-starter-kit.git
$> cd polymer-starter-kit/
$> npm install
$> bower install
$> gulp
$> ls dist/images/touch
<empty>
```

Platform: OSX (10.11.1 Beta (15B38b))
Node: v0.10.21
Gulp: 3.9.0

**Comment by addyosmani** [comment] 2015-10-21 08:53
Thanks. Confirmed. Dupe of https://github.com/PolymerElements/polymer-starter-kit/issues/257

**Closed by addyosmani** 2015-10-21 08:53 UTC
Labels: build-process
