### ISSUE TITLE
_pageChanged Error on Safari - Polymer v2

### ISSUE THREAD

**Issue by tgensol** [PolymerElements/polymer-starter-kit#996] opened 2017-04-04 13:55 UTC
Hi there,

in the Polymer 2.0 starter kit, the _pageChanged is not working on Safari, every time the _showPage404 method is called (I can see that successively onSuccess and the onError are called). But it is working fine on Chrome. 

After the app is "init" (like the showPage404 displayed once), the _pageChanged works fine

### Expected outcome

http://127.0.0.1:8081/ should display the view 1 component, or
http://127.0.0.1:8081/view3 should display the view 3 component

### Actual outcome

Oops you hit a 404. Head back to home.

### Browsers Affected

- [ X ] Safari 10
- [ X] Ios 10

Any idea ?
Regards

**Comment by stramel** [comment] 2017-06-01 17:37
Related to #991

**Comment by abdonrd** [comment] 2017-07-21 07:33
I think it's fixed in master. Let me know if the problem persists!

**Closed by abdonrd** 2017-07-21 07:33 UTC

**Comment by zhen1991** [comment] 2018-06-15 10:37
Hi guys!
I am facing this problem on my iphone i have ios version 11 so ithink teh safari also is anew versioin :)
can u give me tips about how to fix this :)

**Comment by zhen1991** [comment] 2018-06-15 11:02
@abdonrd  can you please describe what u mean by master

**Comment by abdonrd** [comment] 2018-06-15 11:58
@zhen1991 did you try with the last PSK version?

with Polymer 2: https://github.com/Polymer/polymer-starter-kit/releases/tag/v3.2.1
with Polymer 3: https://github.com/Polymer/polymer-starter-kit/releases/tag/v4.0.0

**Comment by zhen1991** [comment] 2018-06-15 12:40
@abdonrd i tried to update and isntall new version of bower but it didnt fix my issue
i still get the 404 errror !

**Comment by abdonrd** [comment] 2018-06-15 13:26
@zhen1991 how are you serving the project? Locally with `polymer serve`?

**Comment by zhen1991** [comment] 2018-06-15 13:30
@abdonrd yes i run polymer serve --compile never !
but the problem only occure on safari when i run my app i dont have this problem on android!
thnx for answering:)

**Comment by abdonrd** [comment] 2018-06-18 14:44
@zhen1991 any logs in the Dev Tools?

**Comment by zhen1991** [comment] 2018-06-19 07:13
@abdonrd my problem occure if I refresh the browser I get a 404 ERROR. otherwise i dont face this problem and its only occure in ios :)
i tried some solution like to add the subdirectory path to your URLs. but it didnt fix it:)
thnx:)

**Comment by abdonrd** [comment] 2018-06-19 13:27
I can't reproduce the error. The project is public somewhere?

**Comment by zhen1991** [comment] 2018-06-20 14:02
Hi!
i have fixed by adding hashtag to my url :)
