### ISSUE TITLE
jshint refers to *.html-script-0

### ISSUE THREAD

**Issue by zboralski** [PolymerElements/polymer-starter-kit#531] opened 2015-11-23 15:21 UTC
jshint output from gulp serve refers to *.html-script-0.

**Comment by zboralski** [comment] 2015-11-23 15:22
The line numbers are useless. jshint should be ran on the original files instead.

**Comment by samccone** [comment] 2015-11-23 17:37
:+1: I agree this does seem bad, can you post the full error and how to reproduce?

**Comment by jparish3** [comment] 2015-12-06 20:26
Not sure if related, but now getting the following error on element used in prior starter kit versions (pre-1.2)  without error:
[15:19:25] 'lint' errored after 2.03 s
[15:19:25] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: app/elements/test-search/test-search.html-script-0

**Comment by robdodson** [comment] 2015-12-06 21:22
> The line numbers are useless. jshint should be ran on the original files instead.

hmm, I thought it was running only against [the original files](https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L110-L115)

quick question: are either of you using external javascript files for your elements?

**Comment by robdodson** [comment] 2015-12-07 01:35
I just ran into this while using the ES2015 recipe. Are either of you trying to do that or are you hitting this error on just a vanilla version of the app?

**Comment by cnbuff410** [comment] 2015-12-07 04:32
I tried ES2015 recipe and ran into this issue as well.

**Comment by jparish3** [comment] 2015-12-07 15:39
I am adding a slightly modified version of this element: https://github.com/kunalkundaje/address-autocomplete from the app/elements folder. it does not appear to be a bower package, so bringing it in manually

**Comment by jesusabarca** [comment] 2015-12-08 18:43
I just got that same error after updating to 1.2.1

```
[12:35:51] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: app/scripts/app.js, app/elements/house-data/house-data.html-script-0, app/elements/house-markers/house-markers.html-script-0, app/elements/log-in/log-in.html-script-0
[12:35:51] gulp-imagemin: Minified 6 images (saved 494 B - 1.4%)
```

**Comment by robdodson** [comment] 2015-12-08 19:43
I'm guessing one possible solution would be to tell jshint to ignore *.html-script-* files but I'd like to know what's creating them :D

**Comment by jesusabarca** [comment] 2015-12-08 21:29
@robdodson I'm new on this, so I don't really know how to troubleshoot it. Any suggestions would be much appreciated ;)

**Comment by robdodson** [comment] 2015-12-09 01:58
@jesusabarca in the short term just disable the lint task (remove it from being called in default or serve or anywhere else). I'll work on a fix tomorrow

**Comment by samccone** [comment] 2015-12-09 02:25
I also will look into this one, sorry about this issue

**Comment by jesusabarca** [comment] 2015-12-09 17:26
Thanks guys, you rock.

**Comment by klarkc** [comment] 2015-12-11 12:58
Same here:
```
[09:51:00] Starting 'lint'...

/home/klarkc/Sources/frontend-vagas/app/elements/fic-menu/fic-menu.html-script-0
  line 3   col 10  Expected indentation of 10 characters
  line 5   col 10  Expected indentation of 10 characters
  line 6   col 12  Expected indentation of 12 characters
...
```

**Comment by robdodson** [comment] 2015-12-11 16:55
@klarkc thanks klarkc. We're looking into this today.

**Comment by samccone** [comment] 2015-12-11 18:45
Hey all!

So I did some digging here, let me first clarify two points :point_left: 

1. this is not related to any recipe in particular
2. these are valid errors and you will only get them if your code does not pass lint

--------

So you might be like what even are these messages? well, lets disect exactly what it is saying when we take a second and read the error :warning: :flags: 

![screen shot 2015-12-11 at 10 40 45 am](https://cloud.githubusercontent.com/assets/883126/11752305/aae59ae6-9ff3-11e5-89f3-31ef030dab81.png)

![screen shot 2015-12-11 at 10 41 48 am](https://cloud.githubusercontent.com/assets/883126/11752343/ef0bb1b0-9ff3-11e5-8847-7bb1eea0b85b.png)

-

Hey this is actually super valuable :tada: 

Now, I agree that this error is not exactly the most "human" of messages however... that is something we can fix up/cross stream to this issue, so I am going to close this and open up a new issue to track improving the readability of our error messages...

Thanks all for the feedback here :dancers:

**Closed by samccone** 2015-12-11 18:45 UTC
Labels: build-process

**Comment by Royedc4** [comment] 2015-12-17 12:04
@samccone Hey, I find out a few errors with this lint task. You are right those issues like single quotes for strings are a quick fix BUT I'm getting are error like THIS.

![screen shot 2015-12-17 at 07 22 09](https://cloud.githubusercontent.com/assets/1709472/11869097/ed99f694-a48e-11e5-9bd0-a72afd815a19.png)

I Figure it out that the problem was that my IDE (WebStorm) after format the entire file generate a white space between the function definition and the round brance example.

![screen shot 2015-12-17 at 07 30 12](https://cloud.githubusercontent.com/assets/1709472/11869216/1e5d4c6c-a490-11e5-9f30-91f41ec91fa1.png)

It's really annoying, because obviously I'm getting the problem in all the files, for now I will disable the lint task, but It will be really important to look at it.

Let me know and I will review at it anytime.

**Comment by klarkc** [comment] 2015-12-17 12:46
A little tip that helped me, use the [EditorConfig](http://editorconfig.org/) plugin for your IDE. The IDE can read the PSK .editorconfig and format code accordingly.

Bonus:
1. If you use a plugin or IDE that uses http://jsbeautifier.org/ that is my personal .jsbeautifyrc file to format the code:
```json
{
    "js": {
        "space_after_anon_function": false,
        "space_before_conditional": true,
        "end_with_newline": true
    }
}
```
2. For Brackets IDE I use this .brackets.json configuration file:
```json
{
    "interactive-linter.javascript": ["jshint"],
    "linting.prefer": [
      "JSHint",
      "JSCS"
    ]
}
```

**Comment by globalepub** [comment] 2016-01-07 11:59
Hello guys,

I am using Notepad++  and having the same issue. Pls your support.

![expected indentation - pol](https://cloud.githubusercontent.com/assets/1713570/12170082/00f457ea-b536-11e5-9db6-46e8f09d6db0.png)

**Comment by samccone** [comment] 2016-01-07 16:56
hi @globalepub please refer to this answer
https://github.com/PolymerElements/polymer-starter-kit/issues/531#issuecomment-164014900

**Comment by globalepub** [comment] 2016-01-07 17:10
Hi Samccone,

Of course I referred to all these answers but the issue still be. 
The issue is that I've added new data to this file.

**Comment by robdodson** [comment] 2016-01-07 19:09
@globalepub You need to make sure you have the following changes:

Your gulpfile should include this `strip` option:
https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L133

Your `package.json` should include the latest `gulp-html-extract`:
https://github.com/PolymerElements/polymer-starter-kit/blob/master/package.json#L13

I'd recommend you delete `node_modules` and run `npm install` again after you've made that change to `package.json`

**Comment by jparish3** [comment] 2016-01-07 23:05
I completed the suggested steps above and still get: [17:32:48] Error in
plugin 'gulp-jshint'
Message:
    JSHint failed for: app/elements/address-autocomplete.html-script-0 with
PSK-1.20.
I cannot replicate the errors on http://jshint.com/ or using Atom packages.
After posting the earlier issue, I turned off jshint and the element works
fine.
I see that this issue is closed. Should I continue to disable jshint?

**Comment by robdodson** [comment] 2016-01-07 23:37
is that the entire error message? Usually jshint will report what part of the file failed

**Comment by jparish3** [comment] 2016-01-08 01:43
there were 15 warnings (attached); many repeat and I was unable to
replicate any within other jshint applications except http://www.jslint.com/
but this app threw entirely different errors on the same script. Thanks

**Comment by robdodson** [comment] 2016-01-08 17:30
@jparish3 not seeing any warnings

**Comment by jparish3** [comment] 2016-01-08 18:18
i thought this message:   ⚠  15 warnings was relating to the following:
line 40  col 19   Illegal space after opening curly brace
  line 40  col 38   Illegal space before closing curly brace
  line 44  col 103  Line must be at most 100 characters
  line 57  col 183  Line must be at most 100 characters
  line 60  col 108  Line must be at most 100 characters
  line 64  col 32   Illegal space before opening round brace
  line 65  col 14   All identifiers must be camelCase or UPPER_CASE

 There is a total of 15 altogether which are included in the pdf attachment
from prior response...hope that came through

**Comment by robdodson** [comment] 2016-01-08 19:51
@jparish3 ah, you can't attach files to github issues.

So, those warning just look like you're failing jshint. You might look at the `.jshintrc` file which lists all of the rules.

**Comment by jparish3** [comment] 2016-01-09 16:45
thanks.I will take a look. are these rules new to PSK 1.2? This element (
https://github.com/kunalkundaje/address-autocomplete) worked fine in prior
versions and still runs without issue in 1.2 if jshint is deactivated. I
would appreciate any clarification, as this parsing functionality is a core
element within our app. I have checked out the script using other linting
apps and compared the code to a similar bower package for angular.
Everything seems to check out but I am new to this space and committed to a
Polymer build, so do not want to ignore the jshint warnings.

**Comment by robdodson** [comment] 2016-01-10 21:23
I don't know if jshint was properly running over all of the elements in previous releases.

Because jshint is configurable, if you don't provide the same settings to your online jshint tool it may not report the same errors as PSK. The settings are located in `.jshintrc`.

JSHint is just meant to be a code quality tool, so if you find certain settings too restrictive you can always change them, or turn the task off entirely if you feel like living la vida loca :dancer: 

I think right now the warnings are probably accurate as I can see some instances in your source which would trigger a warning. For instance:

A rule like `Illegal space before opening round brace` means your function's should look like this:

`function() { ... }` and not have a space before the parenthesis, like this: `function () { ... }`

Looking at your example file, it seems like [this line would fail that](https://github.com/kunalkundaje/address-autocomplete/blob/master/address-autocomplete.html#L123)

Again, if you find the rules restrictive or annoying then change them to meet your needs or turn certain ones off. The goal is just to give you consistent code quality.

**Comment by jparish3** [comment] 2016-01-11 03:23
Thanks.  Appreciate the perspective (and the Ricky Martin you tube)
