### ISSUE TITLE
Internet Explorer style issues in PSK 1.2.0

### ISSUE THREAD

**Issue by ghost** [PolymerElements/polymer-starter-kit#550] opened 2015-12-02 09:55 UTC
There are some heavy style issues in internet explorer for the new PSK. (See attachment).
![untitled](https://cloud.githubusercontent.com/assets/13914108/11527782/2d1d1e3e-98e3-11e5-9395-dfb0f11e4656.png)

**Comment by addyosmani** [comment] 2015-12-02 09:58
Which version of IE are you testing against?

**Comment by BorntraegerMarc** [comment] 2015-12-02 11:31
Newest version of internet explorer 11 and experience the same issue on edge.

**Comment by chuckh** [comment] 2015-12-02 16:11
I got the same results on Windows 10 using IE 11 and Edge. Not sure if it is a PSK issue or up stream issue.

**Comment by BootsSiR** [comment] 2015-12-03 01:16
I started to make an application with PSK about four days ago and just out of curiosity, I opened it up in IE 11/Edge and it's badly broken.  The first two menu items in the drawer don't show up on load, however if I resize the window, they pop into view.  Also navigation doesn't seem to work.  I don't get any javascript errors in the console but it seems badly broken.

**Comment by BorntraegerMarc** [comment] 2015-12-03 07:47
@addyosmani Should I open another issue for IE/Edge support in general? And if yes, where should i open it?

**Comment by addyosmani** [comment] 2015-12-03 10:47
We can use this issue for it. Atm, we'll need to assess if this is an issue with PSK itself or whether this was caused by one of the `paper-*` dependencies we use. 

We'll want to test:

https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/transform-header-5.html&active=paper-scroll-header-panel

https://elements.polymer-project.org/elements/paper-drawer-panel?view=demo:demo/index.html&active=paper-drawer-panel

https://elements.polymer-project.org/elements/paper-menu?view=demo:demo/index.html&active=paper-menu

for breakage

**Comment by BorntraegerMarc** [comment] 2015-12-03 12:27
So I've tested the pages and attached the screenshots (always IE first)... It looks like edge can handle every good. The layout seems right and it behaves as it should... Although IE can't even display the element.
![image](https://cloud.githubusercontent.com/assets/13914108/11560523/6c9449fa-99c1-11e5-89d8-574d67bf98ea.png)

![image](https://cloud.githubusercontent.com/assets/13914108/11560529/71731096-99c1-11e5-96d0-3aa04815a9c8.png)

![image](https://cloud.githubusercontent.com/assets/13914108/11560535/76c5b8aa-99c1-11e5-9722-dd73a762b3fa.png)

![image](https://cloud.githubusercontent.com/assets/13914108/11560543/84293f9e-99c1-11e5-832c-7d7a370214e5.png)

![image](https://cloud.githubusercontent.com/assets/13914108/11560545/898e078a-99c1-11e5-8a32-54050464c971.png)

![image](https://cloud.githubusercontent.com/assets/13914108/11560546/901cd3ec-99c1-11e5-85eb-a14e46b06a74.png)

**Comment by BorntraegerMarc** [comment] 2015-12-03 12:31
I updated polymer from V. 1.1.0 to 1.2.1 and my page looks now like this:
![image](https://cloud.githubusercontent.com/assets/13914108/11560616/ff888fc8-99c1-11e5-8d68-15b17207dec1.png)

And on chrome:
![image](https://cloud.githubusercontent.com/assets/13914108/11560623/08397e16-99c2-11e5-985c-dba4e2409480.png)

**Comment by chuckh** [comment] 2015-12-03 15:02
I see this problem now also. You can see the problem live at http://polymerelements.github.io/polymer-starter-kit/.

This does not happen on https://polymer-starter-kit.firebaseapp.com/ which was built a couple days ago using 1.2.0. Might be an upstream issue related to deprecating /deep/ work going on now. See https://blog.polymer-project.org/announcements/2015/12/01/deprecating-deep/.

**Comment by ngeshlew** [comment] 2015-12-08 07:11
So what has been the conclusion to this issue?

**Comment by robdodson** [comment] 2015-12-08 21:30
I don't think anyone has had time to look at it. I'll bump the priority

**Comment by chuckh** [comment] 2015-12-10 22:37
This pr might fix this problem: https://github.com/PolymerElements/paper-scroll-header-panel/pull/74.

Slack conversion regarding this:

12/10/15
> amitmerin [12:38 PM] 
Hi, I am working on a project based on the polymer starter kit. Unfortunately I need to make it work on IE11, but as you can see on the team's demo http://polymerelements.github.io/polymer-starter-kit/ the `<paper-toolbar>` is hiding part of the content, making it inaccessible. Any idea how to solve this?(edited)

> westbrook [12:50 PM] 
@amitmerin: interesting, it seems to measuring in `ready()` instead of `attached()` as is the suggested point in the lifecycle callbacks to do so.  you might test out a patch that just changes the callback to `attached()` and see if it’s better whole sale: https://github.com/PolymerElements/paper-scroll-header-panel/blob/master/paper-scroll-header-panel.html#L298

> GitHub
PolymerElements/paper-scroll-header-panel
paper-scroll-header-panel - Fancy scrolling effects where the header animates between tall and condensed states

> amitmerin [12:51 PM] 
@westbrook: Thanks, I will take a look at that

> westbrook [12:53 PM] 
that may also allow for the removal of `this.async()` that is wrapping `this.measureHeaderHeight()` which is where the discrepancy in IE comes from.

> amitmerin [12:56 PM] 
@westbrook: Changed `ready` to `attached` on the `paper-scroll-header-panel.html` page and it worked. :+1:

> westbrook [12:57 PM] 
you should confirm across browsers and submit the PR!

> ​[12:58] 
seems more like an oversight than a feature, but i couldn’t be sure.

> ​[1:01] 
@emmanuel: do you have any thoughts on this ^——?

> emmanuel [1:06 PM] 
@weavemn: will take a look

> ​[1:07] 
that sounds like it should be `attached` instead of `ready`

> westbrook [1:07 PM] 
yeah, i just put in a PR after amitmerin helped confirm it looks good across browsers.

**Comment by Westbrook** [comment] 2015-12-11 15:24
@chuckh this is definitely what we were looking into with that PR/convo.  i think i've covered all of the notes from @blasten at this point, so hopefully the merge is good to be put through soon.

**Comment by chuckh** [comment] 2015-12-21 15:16
With the latest PSK on Windows 10 using IE 11 is usable, but menu highlight is off. Microsoft Edge now works ok.  PolymerElements/paper-scroll-header-panel#74 has been merged.

Windows 10 using IE 11 :frowning: 
![image](https://cloud.githubusercontent.com/assets/19915/11933681/0c9a7d4a-a7b2-11e5-9d1a-85d96b44bb44.png)

Windows 10 Edge :smile: 
![image](https://cloud.githubusercontent.com/assets/19915/11933724/55ea7356-a7b2-11e5-9d5a-42ccd1434b18.png)

**Comment by robdodson** [comment] 2016-01-10 22:48
hmmmm I wonder if that's specific to our use of paper-item or if they all suffer from this same issue in IE11.

**Comment by chuckh** [comment] 2016-01-10 23:24
The master is using the current version of paper-item and paper-menu.  See https://github.com/PolymerElements/polymer-starter-kit/blob/master/bower.json. 

Looks like it is a problem with paper-menu and IE 11 see screenshot below.  Demo works fine with MS Edge.

We are using paper-menu with a tags instead of paper-item.
```
 <paper-menu attr-for-selected="data-route" selected="[[route]]">
          <a data-route="home" href="{{baseUrl}}">
            <iron-icon icon="home"></iron-icon>
            <span>Home</span>
          </a>
         ...
        </paper-menu>
```

## Windows 10 IE 11 paper-menu demo
![image](https://cloud.githubusercontent.com/assets/19915/12224780/7112ed2e-b7ad-11e5-8f7c-c69787d4a34f.png)

**Comment by robdodson** [comment] 2016-01-10 23:51
Hm ok so this seems like we need an upstream fix then, yeah? @cdata have you seen this before?

**Comment by robdodson** [comment] 2016-08-27 16:36
@chuckh do you know if any of these issues related to paper-item still exist in PSK2?

**Comment by chuckh** [comment] 2016-08-28 14:26
@robdodson we don't have this issue with PSK2 since we are using `iron-selector` instead of `paper-menu`.  

## PSK2 Screenshot with View Two selected (IE 11)
![image](https://cloud.githubusercontent.com/assets/19915/18033902/0c705464-6ce4-11e6-8065-1178133e3186.png)

## Paper-menu and paper-item demo screenshot (not working)
![image](https://cloud.githubusercontent.com/assets/19915/18033911/3f1cd626-6ce4-11e6-98a4-4ba5014e29c3.png)
Tested using: http://polygit.org/components/paper-menu/demo/index.html

So using `paper-item` with `paper-menu` still has formatting issues with MS IE 11, but it is not a PSK issue.

**Closed** 2016-11-02 18:12 UTC
Labels: bug, P1, waiting-on-upstream-fix
