### ISSUE TITLE
CSS not applied to header in Chrome mobile emulator

### ISSUE THREAD

**Issue by bkawk** [PolymerElements/polymer-starter-kit#988] opened 2017-03-20 09:04 UTC
<img width="426" alt="screen shot 2017-03-20 at 4 21 18 pm" src="https://cloud.githubusercontent.com/assets/14357697/24093627/bdfc4fe8-0d8f-11e7-9655-c336c17d7856.png">
### Description
Missing styles from the header in mobile dvice in Chrome

### Expected outcome

I expect to see a blue styled header

### Actual outcome

The header has no styles applied 

### Steps to reproduce

1. Using the latest polymer CLI.
2. Making a fresh application, by using "polymer init" of the polymer start kit 2, 
3. Serve the default application with "polyserve"
4. Open the Chrome dev tools and toggle to iPhone device
5. Refresh the page
6. Notice the header has no style, no blue header and no console error's

### Browsers Affected

- [ x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by clark-stevenson** [comment] 2017-05-12 07:08
I also get this issue when starting a new polymer project with the latest cli.    

Basically any IOS Emulation does as above.  Other selections such as Galaxy appear unaffected.

**Comment by abdonrd** [comment] 2017-06-01 19:56
@bkawk I cant reproduce. Can you try with the last version? Thanks!

**Comment by abdonrd** [comment] 2017-06-15 16:42
Closing now. Ping me if you can reproduce to reopen.

**Closed by abdonrd** 2017-06-15 16:42 UTC
