### ISSUE TITLE
Installing PSK takes 200mb of disk space

### ISSUE THREAD

**Issue by Beldur** [PolymerElements/polymer-starter-kit#765] opened 2016-03-29 14:51 UTC
### Description

Installing PSK takes 200mb+ of disk space. This puts a lot of bandwidth pressure on a CI server that builds the project on each commit.

What is the best practice here when running in an CI environment? Should there be a `npm install` on each commit that downloads hundreds of megabytes? Should I use a local npm registry cache?

### Expected outcome

A simple HTML/Javascript/CSS app should not go into the hundreds of megabytes as a start

### Actual outcome

After `npm install` and `bower install` the required space for the PSK is 200mb+.

### Steps to reproduce

1. Download PSK
2. Follow installation steps

**Comment by samccone** [comment] 2016-03-29 15:09
duplicate of #337
Thanks for opening this @Beldur :)

Let's continue the conversation over in 337

**Closed by samccone** 2016-03-29 15:09 UTC
