### ISSUE TITLE
Fullbleed creates an extra scroller

### ISSUE THREAD

**Issue by emersonbottero** [PolymerElements/polymer-starter-kit#271] opened 2015-07-24 18:04 UTC
I don`t think it is the correct behavior, if you remove fullbleed from line 58 it works using the hole area but without the extra scroller.

**Comment by addyosmani** [comment] 2015-07-28 09:40
Do you have a test case that reproduces this that you can share? Even if it's just the output of your index.html file, that should be enough for us to test what you're seeing.

**Comment by emersonbottero** [comment] 2015-07-29 01:50
just run the Polymer starter Kit as it is and you will see!
run gulp serve in it whitout any changes! Only in chrome in windows! 
![psk](https://cloud.githubusercontent.com/assets/12377432/8948208/ed7c33bc-357a-11e5-9548-91c58c4514c0.png)

**Comment by addyosmani** [comment] 2015-07-29 08:54
Ah! Can repro in Chrome for Windows. Marking as a bug. This may end up being an upstream issue but we'll investigate further.

**Comment by SayChunKim** [comment] 2015-07-29 09:15
Try uncomment the height:900px of the content in app-theme.html instead of removing fullbleed, see whether problem reproduced? @emersonbottero

**Comment by emersonbottero** [comment] 2015-07-29 23:10
still the same after removing 
height:900px

**Comment by chuckh** [comment] 2015-09-01 17:14
I just tested with PSK master with Windows Chrome 44 no extra scrollbars. Seems to be fixed. @addyosmani does it work for you now?

![image](https://cloud.githubusercontent.com/assets/19915/9610985/e6df5dea-5091-11e5-975e-146c8fa11227.png)

**Comment by addyosmani** [comment] 2015-09-01 17:23
This is working for me now. Feel free to re-open if this is still an issue in master for anyone!

**Closed by addyosmani** 2015-09-01 17:23 UTC
Labels: bug, question

**Comment by emersonbottero** [comment] 2015-09-23 00:46
It's is back again in PSK 1.1.0 Chrome 45 + Windows 10
![image](https://cloud.githubusercontent.com/assets/12377432/10035665/2c432474-6173-11e5-8950-815864a2ce5b.png)
