### ISSUE TITLE
Error in Chrome, Uncaught TypeError: Cannot read property 'whenReady' of undefined polymer.html 4192

### ISSUE THREAD

**Issue by mypark** [PolymerElements/polymer-starter-kit#348] opened 2015-09-08 14:06 UTC
Just downloaded the polymer-starter-kit-light-1.0.3 and am seeing this error in Chrome. Oddly enough it seemed to have worked without problems just a few days ago. It works fine in Safari. What could have changed with chrome to suddenly start causing this error?

Uncaught TypeError: Cannot read property 'whenReady' of undefined polymer polymer.html:4192

**Comment by robdodson** [comment] 2015-09-08 15:36
are you still running the local server with gulp? It seems like possibly Polymer isn't loading?

**Comment by addyosmani** [comment] 2015-09-08 18:14
As Rob mentioned it appears that this is an issue with Polymer not loading. Can you try loading PSK light up in an incognito window and let us know if you see the same thing? The package hasn't changed since it was published.

**Comment by mypark** [comment] 2015-09-09 01:52
it works in the incognito window - but still doesn't work in regular chrome... why is that?

**Comment by robdodson** [comment] 2015-09-09 02:40
@mypark possibly service worker interference?

**Comment by pantaluna** [comment] 2015-09-09 08:02
@mypark 
a. Chrome Extensions (also check the flag AllowInIncognito for each)
b. chrome://flags/

**Comment by addyosmani** [comment] 2015-09-23 09:58
If this works in Incognito mode, it's very likely that either an extension (please try toggling them on/off to discover which one is to blame) or Service Worker support (you can unregister active Service Workers in about:serviceworker-internals). As we're unable to reproduce this on our end and the above should fix the issue, closing this bug.

**Closed by addyosmani** 2015-09-23 09:58 UTC
