### ISSUE TITLE
Icons not sized properly on initial load

### ISSUE THREAD

**Issue by alexmineer** [PolymerElements/polymer-starter-kit#628] opened 2015-12-28 18:07 UTC
I did a fresh install of the latest 1.2.1 release.  After running gulp && gulp serve the default icon size is huge, see attached screenshot.  Interacting with the icon (e.g. clicking) resizes them correctly; refreshing the page brings the issue back.

<img width="702" alt="screen shot 2015-12-28 at 9 53 58 am" src="https://cloud.githubusercontent.com/assets/16466611/12023079/b9051188-ad4a-11e5-9bc8-155496a70ec2.png">

**Comment by samccone** [comment] 2015-12-28 18:22
I will investigate

**Comment by robdodson** [comment] 2016-01-10 23:44
Testing in Chrome, Firefox, and Safari on Mac doesn't show this issue. @alexmineer which browser/platform are you seeing this on? Also I'm curious if you remove your bower_components directory and run `bower cache clean && bower install` if you still see the issue?

**Comment by samccone** [comment] 2016-01-11 02:19
@alexmineer I am like 98% sure this does not happen in a clean vanilla install of this project.. I just attempted to reproduce under slow network conditions and a few other cases.

I have seen this issue ^ happening IRL however it was due to a stylesheet that a user had added blocking the render of the page in a weird way.

I would see if running this in an incognito window in chrome reproduces the issue... if not I would guess that it might be an issue with a plugin that you have running...

If this is still an issue let me know and with some more details I can help get to the bottom of this.

---

closing for now as unable to reproduce

**Closed by samccone** 2016-01-11 02:19 UTC
Labels: pending-response
