### ISSUE TITLE
gulp test does not work

### ISSUE THREAD

**Issue by MrChoclate** [PolymerElements/polymer-starter-kit#381] opened 2015-09-23 17:05 UTC
Hello

I clone the repo and did: `npm install && bower install && gulp test` and got this long and unreadable error:

```
[choclate@choclate polymer-starter-kit]$ gulp test
[19:03:20] Using gulpfile ~/documents/projects/web/polymer-starter-kit/gulpfile.js
[19:03:20] Starting 'wct:local'...
Installing and starting Selenium server for local browsers
Selenium server running on port 56182
Web server running on port 2000 and serving from /home/choclate/documents/projects/web/polymer-starter-kit
firefox 40               Tests failed: {"state":"unhandled error","sessionId":null,"hCode":941794438,"value":{"additionalInformation":"\nDriver info: org.openqa.selenium.firefox.FirefoxDriver","localizedMessage":"Bad request\nCommand duration or timeout: 98 milliseconds\nBuild info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'\nSystem info: host: 'choclate.salle106.atilla.org', ip: '192.168.253.31', os.name: 'Linux', os.arch: 'amd64', os.version: '3.18.21-1-MANJARO', java.version: '1.8.0_60'\nDriver info: org.openqa.selenium.firefox.FirefoxDriver","supportUrl":null,"systemInformation":"System info: host: 'choclate.salle106.atilla.org', ip: '192.168.253.31', os.name: 'Linux', os.arch: 'amd64', os.version: '3.18.21-1-MANJARO', java.version: '1.8.0_60'","cause":null,"stackTrace":[{"fileName":"NativeConstructorAccessorImpl.java","nativeMethod":true,"methodName":"newInstance0","className":"sun.reflect.NativeConstructorAccessorImpl","hCode":-917798116,"lineNumber":-2,"class":"java.lang.StackTraceElement"},{"fileName":"NativeConstructorAccessorImpl.java","nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.NativeConstructorAccessorImpl","hCode":-1864225098,"lineNumber":62,"class":"java.lang.StackTraceElement"},{"fileName":"DelegatingConstructorAccessorImpl.java","nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.DelegatingConstructorAccessorImpl","hCode":-2122307259,"lineNumber":45,"class":"java.lang.StackTraceElement"},{"fileName":"Constructor.java","nativeMethod":false,"methodName":"newInstance","className":"java.lang.reflect.Constructor","hCode":-1319859920,"lineNumber":422,"class":"java.lang.StackTraceElement"},{"fileName":"ErrorHandler.java","nativeMethod":false,"methodName":"createThrowable","className":"org.openqa.selenium.remote.ErrorHandler","hCode":514255488,"lineNumber":206,"class":"java.lang.StackTraceElement"},{"fileName":"ErrorHandler.java","nativeMethod":false,"methodName":"throwIfResponseFailed","className":"org.openqa.selenium.remote.ErrorHandler","hCode":1091067085,"lineNumber":158,"class":"java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"execute","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":1767885082,"lineNumber":595,"class":"java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"startSession","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":-1182648232,"lineNumber":242,"class":"java.lang.StackTraceElement"},{"fileName":"RemoteWebDriver.java","nativeMethod":false,"methodName":"<init>","className":"org.openqa.selenium.remote.RemoteWebDriver","hCode":2001602308,"lineNumber":128,"class":"java.lang.StackTraceElement"},{"fileName":"FirefoxDriver.java","nativeMethod":false,"methodName":"<init>","className":"org.openqa.selenium.firefox.FirefoxDriver","hCode":2005391580,"lineNumber":223,"class":"java.lang.StackTraceElement"},{"fileName":"FirefoxDriver.java","nativeMethod":false,"methodName":"<init>","className":"org.openqa.selenium.firefox.FirefoxDriver","hCode":2005391573,"lineNumber":216,"class":"java.lang.StackTraceElement"},{"fileName":"FirefoxDriver.java","nativeMethod":false,"methodName":"<init>","className":"org.openqa.selenium.firefox.FirefoxDriver","hCode":2005391491,"lineNumber":134,"class":"java.lang.StackTraceElement"},{"fileName":"NativeConstructorAccessorImpl.java","nativeMethod":true,"methodName":"newInstance0","className":"sun.reflect.NativeConstructorAccessorImpl","hCode":-917798116,"lineNumber":-2,"class":"java.lang.StackTraceElement"},{"fileName":"NativeConstructorAccessorImpl.java","nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.NativeConstructorAccessorImpl","hCode":-1864225098,"lineNumber":62,"class":"java.lang.StackTraceElement"},{"fileName":"DelegatingConstructorAccessorImpl.java","nativeMethod":false,"methodName":"newInstance","className":"sun.reflect.DelegatingConstructorAccessorImpl","hCode":-2122307259,"lineNumber":45,"class":"java.lang.StackTraceElement"},{"fileName":"Constructor.java","nativeMethod":false,"methodName":"newInstance","className":"java.lang.reflect.Constructor","hCode":-1319859920,"lineNumber":422,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultDriverProvider.java","nativeMethod":false,"methodName":"callConstructor","className":"org.openqa.selenium.remote.server.DefaultDriverProvider","hCode":-2096353668,"lineNumber":103,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultDriverProvider.java","nativeMethod":false,"methodName":"newInstance","className":"org.openqa.selenium.remote.server.DefaultDriverProvider","hCode":1201680335,"lineNumber":97,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultDriverFactory.java","nativeMethod":false,"methodName":"newInstance","className":"org.openqa.selenium.remote.server.DefaultDriverFactory","hCode":-1365021416,"lineNumber":60,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultSession.java","nativeMethod":false,"methodName":"call","className":"org.openqa.selenium.remote.server.DefaultSession$BrowserCreator","hCode":2056168471,"lineNumber":222,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultSession.java","nativeMethod":false,"methodName":"call","className":"org.openqa.selenium.remote.server.DefaultSession$BrowserCreator","hCode":2056168250,"lineNumber":1,"class":"java.lang.StackTraceElement"},{"fileName":"FutureTask.java","nativeMethod":false,"methodName":"run","className":"java.util.concurrent.FutureTask","hCode":-820313554,"lineNumber":266,"class":"java.lang.StackTraceElement"},{"fileName":"DefaultSession.java","nativeMethod":false,"methodName":"run","className":"org.openqa.selenium.remote.server.DefaultSession$1","hCode":-255143467,"lineNumber":176,"class":"java.lang.StackTraceElement"},{"fileName":"ThreadPoolExecutor.java","nativeMethod":false,"methodName":"runWorker","className":"java.util.concurrent.ThreadPoolExecutor","hCode":-1285150184,"lineNumber":1142,"class":"java.lang.StackTraceElement"},{"fileName":"ThreadPoolExecutor.java","nativeMethod":false,"methodName":"run","className":"java.util.concurrent.ThreadPoolExecutor$Worker","hCode":-242190645,"lineNumber":617,"class":"java.lang.StackTraceElement"},{"fileName":"Thread.java","nativeMethod":false,"methodName":"run","className":"java.lang.Thread","hCode":-82946320,"lineNumber":745,"class":"java.lang.StackTraceElement"}],"suppressed":[],"message":"Bad request\nCommand duration or timeout: 98 milliseconds\nBuild info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'\nSystem info: host: 'choclate.salle106.atilla.org', ip: '192.168.253.31', os.name: 'Linux', os.arch: 'amd64', os.version: '3.18.21-1-MANJARO', java.version: '1.8.0_60'\nDriver info: org.openqa.selenium.firefox.FirefoxDriver","hCode":1914616627,"class":"org.openqa.selenium.UnsupportedCommandException","buildInformation":{"buildRevision":"411b314","buildTime":"2015-07-30 03:03:16","releaseLabel":"2.47.1","hCode":367960961,"class":"org.openqa.selenium.internal.BuildInfo"},"screen":null},"class":"org.openqa.selenium.remote.Response","status":13}
```

I am on Manjaro and did `yaourt jdk8-openjdk`. 

Any solutions?

**Comment by samccone** [comment] 2015-09-24 01:47
hi @MrChoclate, so this looks to be an issue with connecting to your local firefox via selenium webdriver  via https://github.com/ekryski/launchpad which is perhaps related to https://github.com/SeleniumHQ/selenium/issues/927

I am curious if updating selenium over in wct land https://github.com/Polymer/wct-local/blob/master/package.json will help you / us out.

I am going to close this issue and xpost over in wct land since the root of the issue is there and not here.

**Closed by samccone** 2015-09-24 01:47 UTC
