### ISSUE TITLE
Error: spawn ENOENT after running gulp

### ISSUE THREAD

**Issue by SilverPaladin** [PolymerElements/polymer-starter-kit#122] opened 2015-06-04 22:49 UTC
Windows 7.
```
Download starter kit from Github as zip.
Unzip to folder
npm install (this failed, I can provide log file if you like)
bower install
gulp
```
```
C:\Polymer\polymer-starter-kit-master>gulp
[16:44:49] Using gulpfile C:\Polymer\polymer-starter-kit-master\gulpf
[16:44:49] Starting 'clean'...
[16:44:49] Finished 'clean' after 4.21 ms
[16:44:49] Starting 'default'...
[16:44:49] Starting 'copy'...
[16:44:49] Starting 'styles'...
[16:44:50] 'styles' all files 98 B
[16:44:50] Finished 'styles' after 955 ms
[16:44:54] 'copy' all files 8.2 MB
[16:44:54] Finished 'copy' after 4.79 s
[16:44:54] Starting 'elements'...
[16:44:54] 'elements' all files 0 B
[16:44:54] Finished 'elements' after 6.66 ms
[16:44:54] Starting 'jshint'...
[16:44:54] Starting 'images'...
[16:44:56] Starting 'fonts'...
[16:44:56] Starting 'html'...
[16:44:57] 'fonts' all files 0 B
[16:44:57] Finished 'fonts' after 651 ms
Unhandled rejection Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
[16:44:58] Finished 'jshint' after 4.04 s
[16:44:58] 'html' all files 41.42 kB
[16:44:58] Finished 'html' after 1.53 s
```

**Comment by addyosmani** [comment] 2015-06-05 00:09
Which of the releases did you download?

**Comment by sindresorhus** [comment] 2015-06-05 00:26
I would guess this is the `images` task and that you had some install problems with the `gulp-imagemin` task. Try reinstalling and look closely at the install logging in your terminal.

**Comment by addyosmani** [comment] 2015-06-05 14:17
I'm almost certain this is a dupe of #101. As Sindre mentioned, we're running into a few users having trouble with the image optimisation task. I would leave any additional debug info you might have available in the other ticket so we can nail this down.

I would also recommend trying out the non-checked in dependencies version of the release to see if you have better luck there.

**Closed by addyosmani** 2015-06-05 14:17 UTC
