### ISSUE TITLE
How can i do work Polymer-Starter-Kit with Cordova ?

### ISSUE THREAD

**Issue by SheanYu** [PolymerElements/polymer-starter-kit#919] opened 2016-09-15 16:42 UTC
Hi !

I tried to do work Polymer-Starter-Kit with the Cordova CLI but when i run it on my phone i have a blank page.

I searched on internet but i didn't found, maybe that the answer is hide too deep !

Is there someone know how to do ?

Thanks.
Greetings Loïc.

**Comment by FluorescentHallucinogen** [comment] 2016-10-29 16:55
The problem is in using absolute paths instead of relative. See #905.

**Comment by robdodson** [comment] 2016-10-31 19:57
We did a change in https://github.com/PolymerElements/polymer-starter-kit/pull/940. @SheanYu could you try the master branch and see if it helps?

**Comment by robdodson** [comment] 2016-11-02 18:22
Friendly ping, @SheanYu have you had a chance to try the new version with relative paths?

**Comment by SheanYu** [comment] 2016-11-02 18:56
Greetings @robdodson,

Yes i tried it with the last branch with the relative paths.

I answered on it, it works ! Except that when the application starts i have the error404 page with the redirection. If i follow it then it the router work Well !

Loïc.

**Comment by robdodson** [comment] 2016-12-12 19:47
ok we had to back out the relative paths change because it caused other issues https://github.com/PolymerElements/polymer-starter-kit/pull/940#issuecomment-261645920

This also helped me uncover another bug/feature https://github.com/Polymer/polymer/issues/4213

I am disinclined to make changes to PSK to support Cordova because PSK's primary goal is just to give folks an easy place to play around with Polymer. If we have to jump through hoops for Cordova then I think it would be a better strategy for someone in the community to create a Cordova generator for Polymer CLI that's based on either PSK or the Custom Build generator https://github.com/PolymerElements/generator-polymer-init-custom-build

I'm going to close this issue because I don't think we'll be switching to relative paths anytime soon and that sounds like a deal breaker for Cordova. Instead I'd recommend folks follow the linked Polymer issue from above if they want to track a workaround for this, since it's more of a general Polymer issue and not specific to PSK

**Closed by robdodson** 2016-12-12 19:47 UTC
Labels: pending-response
