### ISSUE TITLE
app directory missing in .bowerrc

### ISSUE THREAD

**Issue by sergiotirado** [PolymerElements/polymer-starter-kit#133] opened 2015-06-07 18:21 UTC
"directory": "bower_components" should be "directory": "app/bower_components" in .bowerrc

https://github.com/PolymerElements/polymer-starter-kit/blob/master/.bowerrc#L2

**Comment by arthurvr** [comment] 2015-06-07 18:32
No, [that's not really true](http://yeoman.io/blog/bower_components-in-project-root.html). Normally you shouldn't run into any issues with this, were you running into any specific problems?

Anyhow, [we're planning to drop the `.bowerrc` file.](https://github.com/PolymerElements/polymer-starter-kit/pull/128)

**Comment by sergiotirado** [comment] 2015-06-07 18:45
Ok. If that's the case, then the issue is to update the links on elements.html to point to bower_components outsude the app directory

https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/elements.html#L12

<link rel="import" href="../bower_components/iron-flex-layout/classes/iron-flex-layout.html">

should become

<link rel="import" href="../../bower_components/iron-flex-layout/classes/iron-flex-layout.html">

**Comment by arthurvr** [comment] 2015-06-07 18:58
If you're using the version of PSK with tooling and `gulp serve` you shouldn't run into any problems.

I could imagine this being a bug in the version without tooling, though. (Haven't tested with the no-tooling version, just brainstorming)

There are already [known problems with the lite version's file paths](https://github.com/PolymerElements/polymer-starter-kit/issues/129).

**Comment by addyosmani** [comment] 2015-06-07 19:20
I believe this is #129 we're running into. I've confirmed it's a paths issue - @sergiotirado could you let us know if this is indeed the light version you're referring to? If so, we should close this as a dupe and aim to solve the issue on that ticket soon.

**Comment by sergiotirado** [comment] 2015-06-07 19:29
I am referring to a version without tooling. On Slack I read others inquiring about this issue because they just downloaded the Polymer Starter Kit, not so much to use it to implement something, but to glance at it to see how it works and learn by peeking into the source code.

**Comment by arthurvr** [comment] 2015-06-07 19:30
> I am referring to a version without tooling.

Ah, that clarifies. Thanks. Let's close this as a dupe then.

**Comment by addyosmani** [comment] 2015-06-07 19:30
Closing as dupe.

**Closed by addyosmani** 2015-06-07 19:30 UTC
