### ISSUE TITLE
The PSK don't save the scroll position when reload

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#722] opened 2016-02-26 15:56 UTC
If you scroll down in any page of the PSK, and reload, you go to the top of the page. :crying_cat_face:

**Comment by robdodson** [comment] 2016-02-26 16:02
Yeah I guess that's a bit intentional:

https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/routing.html#L25-L28

The intention was navigating between pages should reset the position. Didn't think about reloading..

**Comment by abdonrd** [comment] 2016-02-26 16:07
Yes, but I think that the user reload the page, he expect the scroll in the same position, as the browser normal behavior.

What do you think?

**Comment by robdodson** [comment] 2016-02-26 16:19
I agree. We should find a solution that satisfies both use cases

**Comment by abdonrd** [comment] 2016-02-26 16:21
:+1: 

I'm not sure if it's a Polymer general issue, but the Catalog has the same problem: https://github.com/Polymer/polymer-element-catalog/issues/249

**Comment by robdodson** [comment] 2016-02-26 16:23
Yeah it's not polymer specific I don't think. When you're changing pages in a single page app you do want it to scroll to the top (imagine clicking on a different catalog element and it starting halfway down the page). But if you reload it shouldn't do the scroll top.

**Comment by abdonrd** [comment] 2016-02-26 16:25
Yes, you are right! The issue is with the SPA.

**Comment by samccone** [comment] 2016-03-03 04:40
closing this as this is the nature of SPAs ... if anyone can think of a better way to handle it we are all ears and will implement it :)

**Closed by samccone** 2016-03-03 04:40 UTC

**Comment by abdonrd** [comment] 2016-03-03 18:39
Okey!, but I think that we need to find a solution for this problem in the PSK v2.

**Comment by samccone** [comment] 2016-03-03 19:07
open to research and any ideas :)

**Comment by joryphillips** [comment] 2016-03-03 23:21
I've tended towards disabling scrollToTop in the couple apps I've been working on. I'm ok with maintaining vertical position on the screen when the user navigates between routes, and I'd argue that there are cases where this is more friendly.  

Interestingly, reloads still cause my pages to lose scroll position, despite scrollToTop being commented out. What is causing that? Is it inherent to page.js or something?

**Comment by samccone** [comment] 2016-03-03 23:30
If you are doing client side rendering the jump us probably being caused by the initial page height being way less than the height of the page post render :goat:

**Comment by abdonrd** [comment] 2016-03-06 09:00
We have exactly the same problem if we "go back".
