### ISSUE TITLE
Polymer Starter Kit Demo Does Not Work in Chrome

### ISSUE THREAD

**Issue by paranoid-android** [PolymerElements/polymer-starter-kit#561] opened 2015-12-04 11:54 UTC
Hello,

The [Polymer Starter Kit Demo](http://polymerelements.github.io/polymer-starter-kit/) does not render properly in Chrome. The menu items are not spaced properly. In addition, the refresh and search icons are left-aligned instead of right-aligned.

I am experiencing this issue in: 

Chrome v: 47.0.2526.73 (64-bit)
Mac OS X El Capitan

**Comment by chuckh** [comment] 2015-12-04 14:53
Looks like  `iron-flex-layout` version 1.2.2 is causing the problem. Reverting back to 1.2.1 seems to fix it.  I am working on temporary fix reverting back to version 1.2.1 now.

**Comment by chuckh** [comment] 2015-12-04 16:29
You can see this issue on master branch by doing a `gulp serve:dist`, it does not happen with `gulp serve`.

Also, I manually deployed to  [Polymer Starter Kit Demo](http://polymerelements.github.io/polymer-starter-kit/) this fix. It fixes menu issues for Chrome, Firefox and Safari, but not IE11 and Edge issue #550.

**Comment by addyosmani** [comment] 2015-12-05 11:05
Sounds like we need to tag a patch release to address this now that the above commit is in master.

**Comment by opus1269** [comment] 2015-12-08 10:05
I have the same issue in another app. The problem is with call to minifyInline. Something in the refactoring of iron-flex-layout CSS selectors is causing issues. You can use the css: false option in minifyInline to fix it for now.

```js
// vulcanize for production
gulp.task('vulcanize', function() {
	return gulp.src(path.elements.src + 'elements.html')
	.pipe(plugins.vulcanize({stripComments: true, inlineCss: true, inlineScripts: true}))
	.pipe(plugins.crisper({scriptInHead: false}))
	.pipe(plugins.if('*.html', plugins.minifyInline({css: false}))) // can't handle polymer css
	.pipe(plugins.if('*.js', plugins.uglify()))
	.pipe(gulp.dest(path.elements.dist));
});

**Comment by robdodson** [comment] 2015-12-08 13:27
We removed minifyInline in the most recent release to fix this

**Comment by opus1269** [comment] 2015-12-08 19:01
I found the root cause of this and submited an issue on iron-flex-layout:
https://github.com/PolymerElements/iron-flex-layout/issues/60

**Comment by addyosmani** [comment] 2015-12-09 10:40
This issue should be (for now) addressed in the 1.2.1 release available from the Releases page.

**Comment by robdodson** [comment] 2015-12-09 16:25
@addyosmani are you thinking we should close it?

**Comment by samccone** [comment] 2015-12-09 16:27
yep :+1: going to close for now, @opus1269 let us know if the upgrade does not work for you.

**Closed by samccone** 2015-12-09 16:27 UTC
