### ISSUE TITLE
pngs in App/images, not moving into Dist/images

### ISSUE THREAD

**Issue by gedw99** [PolymerElements/polymer-starter-kit#422] opened 2015-10-08 11:38 UTC
**Environment**
node v0.12.7
polymer tag 1.1.1
OSX

**Die problemo !**
Its very simple, but gulp is just not copying the pngs (chrome-touch-icon-192x192.png for eg) from app/images --> dist/images

I tried a gulp clean. No luck

i just some more checks. Its very flackey, so images get copied and not others.
I think there must be some caching going on somewhere. Gulp being too smart ??

Any ideas ??

**Comment by addyosmani** [comment] 2015-10-08 18:13
Interesting. Could you try reinstalling your dependencies `npm cache clean && npm install` and then run `gulp` again to see if that improves the copying situation?

I just pulled PSK master and it appears to be copying the images to dist correctly (OSX here too):

<img width="442" alt="screen shot 2015-10-08 at 19 10 52" src="https://cloud.githubusercontent.com/assets/110953/10375453/8a458c54-6df0-11e5-81e3-c9c939140599.png">

**Comment by gedw99** [comment] 2015-10-09 12:52
@addyosmani 

I just tried a new polymer starter kit and it works perfectly.
But thats not what the problem IS.
I have changes the icons in the apps/images dir,
then i delete the dist folder (to be sure)
then i run "gulp"
then in the dist/images, the images are the original ones, NOT the ones in the app/images.

Hence why i mentioned there seems to be caching going on.

**Comment by Dragod** [comment] 2015-10-09 13:16
I had same problem with the chrome-touch-icon-192x192.png

**Comment by gedw99** [comment] 2015-10-09 13:33
I just tried the npm clean and reinstall of npm and bower components

Did not work.
The dist/images has the orginal ones, rather than the ones from app/images

cant work it out

**Comment by samccone** [comment] 2015-10-09 16:35
@gedw99 Do you get any error messages when you run npm i?

**Comment by gedw99** [comment] 2015-10-10 06:46
@samccone 

None.

gedw99-MacBook-Pro:static apple$ pwd
/Users/apple/Workspace/go/src/bitbucket.org/gedw99/berlininfusions-web/static
gedw99-MacBook-Pro:static apple$ npm i
gedw99-MacBook-Pro:static apple$

**Comment by gedw99** [comment] 2015-10-10 06:55
I cross checked that i am not going mad

made a script to copy the images form APP --> DIST, and i then see the real images

not sure whats up.

I also am using the latest gulp script from the latest polymer release:
https://github.com/PolymerElements/polymer-starter-kit/releases/tag/v1.1.1

**Comment by addyosmani** [comment] 2015-10-21 08:54
Believe this is a dupe of https://github.com/PolymerElements/polymer-starter-kit/issues/422

**Comment by gedw99** [comment] 2015-10-21 13:09
Works for me !

Environment:
OSX
node 4.0
PSK 1.1.1

Node modules install is much cleaner now and no issues at all for me. No errors at all.

As far as the bug relating to images in the "touch" folder being copied to the "dist", still did not work. i was wondering if node 4.0 would help :) It did not, so the issue has nothing to do with node.

**Comment by gedw99** [comment] 2015-10-21 13:12
I found a fix the the image problem:
Environment:
OSX
node 4.0
PSK 1.1.1


The problem is the caching. I simple edit to the gulpfile.js file in root of PSK fixed it completely. 
Solutions was to turn off caching :) 

````

/*
var imageOptimizeTask = function (src, dest) {
  return gulp.src(src)
    .pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true
    })))
    .pipe(gulp.dest(dest))
    .pipe($.size({title: 'images'}));
};
*/

var imageOptimizeTask = function (src, dest) {
  return gulp.src(src)
    .pipe($.imagemin({
      progressive: true,
      interlaced: true
    }))
    .pipe(gulp.dest(dest))
    .pipe($.size({title: 'images'}));
};

```` 

Would be good is this goes into PSK 1.1.2.

**Comment by chuckh** [comment] 2015-10-21 17:12
Also svgs don't get copied.

**Closed** 2015-10-29 20:54 UTC
Labels: research
