### ISSUE TITLE
safari click menu bug

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/polymer-starter-kit#276] opened 2015-07-25 21:56 UTC
You need to press twice on a menu item in safari before it selects the page when the menu is expanded.
First its colours grey and then it colours bleu on the second click and go's to the page.

![image](https://cloud.githubusercontent.com/assets/863731/8891402/3ae3b4c2-3328-11e5-9fe5-005c9715e016.png)

**Comment by arthurvr** [comment] 2015-07-25 21:59
Looks similar to https://github.com/PolymerElements/polymer-starter-kit/issues/166.

**Comment by gertcuykens** [comment] 2015-07-25 22:15
Yes looks the same but why is the other one closed?

**Comment by cnbuff410** [comment] 2015-07-26 04:23
Also ran into this. +1

**Comment by chuckh** [comment] 2015-07-26 14:25
It looks like this is a bug with `paper-menu`.  See paper-menu issues:  https://github.com/PolymerElements/paper-menu/issues/27 and https://github.com/PolymerElements/paper-menu/issues/31.

**Comment by cnbuff410** [comment] 2015-07-26 16:26
@chuckh It's a very annoying bug affecting pretty much ALL the site using paper-menu. Do you know if there is anyone in the paper-menu team working on this?

**Comment by arthurvr** [comment] 2015-07-26 16:37
@cnbuff410 Everybody is free to submit a PR. On the while, `+1`, :+1: and alike comments are not going to help ;)

**Comment by cnbuff410** [comment] 2015-07-26 16:43
@arthurvr I disagree. Not everyone who use Polymer or PSK have time or capability to find the bug and make necessary changes. +1, :+1: and alike comments are used for those people to express their desire for a certain issue. It's related to how the team, and the contributors, should prioritize things.

**Comment by robbbz** [comment] 2015-07-26 17:02
Keep in mind that on every such comment ([you're not the only one](https://github.com/isaacs/github/issues/18#issuecomment-29502779)) everybody gets a mail. Sometimes hunderds of people get an email, while they're not the right one to solve the issue.

> Not everyone who use Polymer or PSK have time or capability to find the bug and make necessary changes.

@cnbuff410 And sometimes the team doesn't have eighter. Remember that you're using free and open source software, and thus, not have the right to complain.

> should prioritize things. 

You're not the right person to set priorities here, and in fact nowhere in open source. If you want (tho you shouldn't) use a [proper solution](https://github.com/ryanflorence/github-plusone-extension).

**Comment by cnbuff410** [comment] 2015-07-26 17:39
@robbbz It's silly to say that we, as users of Polymer and PSK, don't have right to complain. 

Here is the thing, we are not complaining about the bug itself. At least for me, there are a couple of road blocking issues in Polymer to prevent me from rolling out my service to my customer, so I just want to know if people in the team are aware of this problem, and if it's in the queue of their task, and if so, what's the rough ETA on this. Heck, what I, and possibly many other people need here is just a offcial reply saying that we are looking at it. I need to know this to justify my decision on selecting Polymer as the major technology for the frontend part in my company. Polymer is 1.0 now and claims to be production ready, this is the feedback any user betting on Polymer deserves. 

Everyone knows this is a open source project in early phase, bugs will happen, people are busy with many repos, blahblahblahblah. We all understand that. What we are doing here is to tell Polymer team that this is an important issue that we, as an individual developer, run into and would like to see it to be addressed ASAP. It might not be as critical as we thought, or it might be more critical than what the developing team thought, it might not be a roadblock for your company, but it might be the reason my company give up on Polymer.

Also, of course I am not the person to set priorities here. That's why I have to use text to express my desire that hopefully Polymer team will see and maybe consider fixing it 1-2 days earlier.

If the targeting customer of Polymer 1.0 is those devs who have time and capacity and capability to fix all the issues they find in Polymer by themselves and contribute back, then please make it clear in the README and I will shut up and find alternatives.

**Comment by arthurvr** [comment] 2015-07-26 17:49
Let's close this as a duplicate of #166. It's another browser but essentially the same bug. 

@robbbz @cnbuff410 Although I still think +1 comments are useless, discussing this adds way more noise and is off-topic. I never wanted it to escalate like this and let's not discuss it here too ;)

**Comment by robbbz** [comment] 2015-07-26 17:59
> It's silly to say that we, as users of Polymer and PSK, don't have right to complain.

You have the right to complain, but do it in a constructive matter. No open source maintainer likes +1 comments. Mostly it's just the reason to [lock](https://github.com/gulpjs/gulp/issues/893#issuecomment-73796385) discussions instead. There are hunderds of examples out there.

I'll say it again, if a ticket is soo important for you, just fix it yourself. Else, be patient and wait a few days. Having devs receive notifications for noise as +1 comments, only takes their time away from actually fixing problems.

> Let's close this as a duplicate of #166. It's another browser but essentially the same bug.

That sounds good to me.

**Comment by addyosmani** [comment] 2015-07-28 10:03
Closing as a dupe of #166.

**Closed by addyosmani** 2015-07-28 10:03 UTC
